### ISSUE TITLE
GUI not showing the named chest, barrel, shulker.

### ISSUE THREAD

**Issue by Herobrine2143** [CyanideX/Unity-Dark#10]
When I **name** the chest or a shulker or a barrel, the GUI does **not show** the name but in the _Base Version_.
![2020-03-04_16 57 09](https://user-images.githubusercontent.com/22053132/75892339-6fc7e080-5e31-11ea-912c-eaabf4210de2.png)
![2020-03-04_16 57 12](https://user-images.githubusercontent.com/22053132/75892342-70607700-5e31-11ea-8070-6e4affc60e59.png)
![2020-03-04_16 57 14](https://user-images.githubusercontent.com/22053132/75892343-70f90d80-5e31-11ea-98f8-6f4c37a3989e.png)
![2020-03-04_16 57 24](https://user-images.githubusercontent.com/22053132/75892344-70f90d80-5e31-11ea-88a1-8453d7db38f7.png)
![2020-03-04_16 57 26](https://user-images.githubusercontent.com/22053132/75892345-7191a400-5e31-11ea-9619-582a533a4c0e.png)
![2020-03-04_16 57 27](https://user-images.githubusercontent.com/22053132/75892348-7191a400-5e31-11ea-8632-0ebcc73aad22.png)

**Comment by CyanideX** [comment]
Sorry for the late reply.

Unfortunately, there is no translation done on custom names which means there is no entry in the lang file that I can adapt to dark mode. 😢 Perhaps in the future I can provide a Unity companion mod to provide such functionality so, at the time being, this will have to remain as is.
