### ISSUE TITLE
About highlighted button overlay color

### ISSUE THREAD

**Issue by SAGESSE-CN** [CyanideX/Unity-Dark#110]
hi, i'm making a dark theme for my mod.
you added a green overlay when the button is highlight, I wonder the ARGB of this color.

**Comment by SAGESSE-CN** [comment]
<img width="230" alt="image" src="https://github.com/Unity-Resource-Pack/Unity-Dark/assets/6903353/674fe713-4950-4eb1-be1b-fe7b2fb437fc">

**Comment by CyanideX** [comment]
Use the eyedropper tool to grab the color. 😂

**Comment by CyanideX** [comment]
![image](https://github.com/Unity-Resource-Pack/Unity-Dark/assets/3106700/9c6fa6b0-d700-41c6-9330-70ef1285c513)

**Comment by SAGESSE-CN** [comment]
I know, but it seems that it is translucent color.

**Comment by CyanideX** [comment]
Just put the color layer above the GUI element and use the color bend mode to apply it. Adjust curves to your liking.
