### ISSUE TITLE
Please add "RoughlyEnoughItems" mod

### ISSUE THREAD

**Issue by KillNagaThul** [CyanideX/Unity-Dark#111]
It is a better MOD than JEI according to my perception

**Comment by CyanideX** [comment]
I thought it already had dark mode. There are assets in their folder for 'recipecontainer_dark'. Are you sure you're not missing a toggle somewhere?

**Comment by CyanideX** [comment]
Added anyway: https://github.com/Unity-Resource-Pack/Unity-Dark/commit/4ce692ef3b7395adb98cff9f475f2e45e8bef394
