### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by KillNagaThul** [CyanideX/Unity-Dark#112]
**Suggestion**
Please support "Simple Uncrafting Table" MOD too

**Comment by CyanideX** [comment]
In the future, please follow the suggestion guide when submitting; this includes link to the mod for easier access.

**Comment by CyanideX** [comment]
Done in https://github.com/Unity-Resource-Pack/Unity-Dark/commit/a83c20e19ba58648640702b946e260f1321dfc70
