### ISSUE TITLE
Missing Status Effect Textures

### ISSUE THREAD

**Issue by SJ1133** [CyanideX/Unity-Dark#24]
Status effect Textures are missing from the inventory.jpg  asset file. Don't know if this is intentional or an oversight :)

Currently using 1.12 version.

**Comment by CyanideX** [comment]
Status effects aren't part of the inventory._png_ texture. If you're using the Unity Shaders pack, they have been removed.

**Comment by SJ1133** [comment]
![Status](https://user-images.githubusercontent.com/8230006/82778793-861c9000-9ea6-11ea-9e55-1760df73e99a.png)

From my understanding these are meant to be a part of it? If not then how do i get the icons? Because i just get the blank icons otherwise.

**Comment by CyanideX** [comment]
Ooh _those_ status effect icons! Unity doesn't touch those.

**Comment by SJ1133** [comment]
Oh. Its strange because if i dont use unity i can see the icons. If i do use it they just appear as a blank.

Here is an Example.
The original textures
![ORIGINALinventory](https://user-images.githubusercontent.com/8230006/82781673-8ae54200-9eae-11ea-967f-4dbcb9d6eb33.png)

VS Unity
![inventory](https://user-images.githubusercontent.com/8230006/82781694-96d10400-9eae-11ea-99b6-5436670b1aec.png)

Located in assets/minecraft/textures/gui/container/inventory.png

**Comment by CyanideX** [comment]
I'm baffled. I don't ever remember seeing those icons there and I've had that same inventory texture for years. I'm surprised nobody has brought this up before. 

In current versions of Minecraft, the status effect icons are a separate texture.

I'll look into it but, since it's for 1.12, I don't think I'll get around to making the changes. Thanks for bringing it to my attention!

**Comment by SJ1133** [comment]
No Worries. I was just as confused as you were. I did make an amateurish attempt to fix it via gimp. 

![inventory](https://user-images.githubusercontent.com/8230006/82789670-c851cb80-9ebe-11ea-8c83-978a9b7c785f.png)
